### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by v-nys** [bbangert/velruse#100]
Title pretty much says it all. Pyramid runs on Python3, so can Velruse be ported?

**Comment by mmerickel** [comment]
Velruse depends on several libraries that haven't been ported yet. It's
certainly a goal though.

**Comment by avanov** [comment]
I'd like to participate in porting velruse onto 3.3 after I finish with FormEncode.

**Comment by mmerickel** [comment]
A lot of this work was just done by @tseaver.

**Comment by tseaver** [comment]
You will need the 'py3-redux' branch of my python-oauth2 fork:

  https://github.com/tseaver/python-oauth2.git

**Comment by mmerickel** [comment]
I am contemplating the work involved in dropping python-oauth2 and picking up oauthlib as it supports both oauth 1 and 2. I'm going to try to look at it later today.
