### ISSUE TITLE
Raise HTTP error code instead of raising exception when csrf fails

### ISSUE THREAD

**Issue by domenkozar** [bbangert/velruse#101]
If something goes wrong and csrf fails (which is not always in case of fraud), it would be much friendly to raise Bad Request 400 error instead of Python exception that results in 500.

**Comment by avanov** [comment]
@iElectric could you provide a reproducible test case of such an error?

**Comment by domenkozar** [comment]
@2nd unfortunately not, but it's generally a good idea to raise 400 instead of just failing :)

**Comment by mmerickel** [comment]
Is this i would regards to the standalone application? If so, I agree this
exception should be caught. However for users of the plug in they can add
their own exception view if hey wish and the fact that they don't is a
documentation problem.

**Comment by domenkozar** [comment]
Is it possible to configure view to catch custom exception that was raised by velruse?

**Comment by mmerickel** [comment]
Of course. It's just an exception. Add an exception view. :-) I will look
into documenting the api though.

**Comment by domenkozar** [comment]
Awesome :) I'll test that and see if I can reproduce the issue.
