### ISSUE TITLE
Missing make_velruse_app function

### ISSUE THREAD

**Issue by FrancoAA** [bbangert/velruse#130]
I clone the master and when i try to run the flask app example i encounter with this error:
Traceback (most recent call last):
  File "myapp.py", line 8, in <module>
    from velruse.app import make_velruse_app
ImportError: cannot import name make_velruse_app

**Comment by mmerickel** [comment]
Whoops, fixed in 2e66871b28e44471d871414a2fab9d7537d15376. It's `make_app`.
