### ISSUE TITLE
Yahoo problems

### ISSUE THREAD

**Issue by cjw296** [bbangert/velruse#15]
Okay, so trying the following YAML config:

"""

Store:
    Type: velruse.store.memstore:MemoryStore

OpenID:
    Realm: http://http://pythonjobs.chrisw.info/
    Endpoint Regex: http://http://pythonjobs.chrisw.info/loggedin

Yahoo: true

OpenID Store:
    Type: openid.store.memstore:MemoryStore
"""

...and the following submitting form:

<form action="/velruse/yahoo/auth" method="post">
<input type="hidden" name="end_point" value="http://http://pythonjobs.chrisw.info/loggedin" />
<input type="submit" value="Login with Yahoo" />
</form>

I get the following error:
"""
Sorry! There is an error with the request we received from the website you are trying to use. Please try again in a few minutes. If this error persists please contact the site administrator. Learn more..
"""

...from the following Yahoo url:

https://open.login.yahooapis.com/openid/op/auth

What am I going wrong?

**Comment by bbangert** [comment]
You shouldn't need to declare Yahoo there, just leave it empty.

**Comment by cjw296** [comment]
Yeah, OK, so the Yahoo doesn't need the "true", but it doesn't appear to make any difference ;-)

I see I forgot to include the submitting form, which looks like this:

<form action="/velruse/yahoo/auth" method="post">
<input type="hidden" name="end_point" value="http://http://pythonjobs.chrisw.info/loggedin" />
<input type="submit" value="Login with Yahoo" />
</form>


Regardless, the error is still the same...

**Comment by cjw296** [comment]
The problem was the garbage (double http://) in the YAML:

"""
Realm: http://http://pythonjobs.chrisw.info/
Endpoint Regex: http://http://pythonjobs.chrisw.info/loggedin
"""
