### ISSUE TITLE
Odd info stored with Google auth against local server

### ISSUE THREAD

**Issue by cjw296** [bbangert/velruse#18]
So, my html form looks like this:

"""

<form action="/velruse/google/auth" method="post"> 
<input type="hidden" name="popup_mode" value="popup" /> 
<input type="hidden" name="end_point" value="http://server2:6543/loggedin" /> 
<input type="submit" value="Login with Google" /> 
</form> 

"""

server2 is only locally accessible.

Authentication appears to work, but the information returned when the token is looked up in the velruse store comes back as:

{'status': 'fail', 'reason': {'code': 0, 'description': 'Missing parameter'}}

...which isn't very helpful :-S

What's happening here and how can we make this information more useful?

**Comment by cjw296** [comment]
<form action="/velruse/google/auth" method="post"> 
<input type="hidden" name="popup_mode" value="popup" /> 
<input type="hidden" name="end_point" value="http://server2:6543/loggedin" /> 
<input type="submit" value="Login with Google" /> 
</form>

**Comment by cjw296** [comment]
wow, okay, I have _no_ idea how to include html in an issue, I'll email it to you...

**Comment by cjw296** [comment]
`<form action="/velruse/google/auth" method="post"> 
<input type="hidden" name="popup_mode" value="popup" /> 
<input type="hidden" name="end_point" value="http://server2:6543/loggedin" /> 
<input type="submit" value="Login with Google" /> 
</form>`

**Comment by cjw296** [comment]
Wow, so you have to use back-ticks to escape html in issues on github... Anyway, there you have the config.

**Comment by mmerickel** [comment]
Closing this issue considering how much has changed in the last 2 years. Sorry!
