### ISSUE TITLE
Minor Documentation Typos

### ISSUE THREAD

**Issue by cd34** [bbangert/velruse#5]
http://packages.python.org/velruse/providers.html#id5   auth' in html snippet
http://packages.python.org/velruse/providers.html#id7   auth' in html snippet
http://packages.python.org/velruse/providers.html#id9   auth' in html snippet
http://packages.python.org/velruse/providers.html#id11  auth' in html snippet

http://packages.python.org/velruse/modules/app.html

Store:
    Redis: true

Should be:

Store:
    Type: Redis   (or Memory)

http://packages.python.org/velruse/modules/providers/facebook.html

Says:  Handle Twitter OAuth

**Comment by cjw296** [comment]
Maybe fork, fix and pull request?

**Comment by cd34** [comment]
These appear to be fixed in the git repo, just not pushed to packages.python.org
