### ISSUE TITLE
Pull requests from kiorky/mobyle2, WTF.

### ISSUE THREAD

**Issue by kiorky** [bbangert/velruse#52]
I have done a lot of work on velruse and splitted my last pull request in small chunks.
Feel free to speak with me on irc (kiorky on #pyramid (freenode))

Those pull requests must be assembled in a logical and dependant order:
- documentation https://github.com/bbangert/velruse/pull/44
- [MERGED] includeme_convention  https://github.com/bbangert/velruse/pull/45
  - providers_hook https://github.com/bbangert/velruse/pull/53
    - introspectable_configuration https://github.com/bbangert/velruse/pull/47
      - introspectable_providers https://github.com/bbangert/velruse/pull/48
- openid_autoconfiguration  https://github.com/bbangert/velruse/pull/46
  - contextual_endpoint https://github.com/bbangert/velruse/pull/51
    - ldap_provider https://github.com/bbangert/velruse/pull/50
- introspectable_configuration / ldap_provider 
  - introspectable_ldap_provider https://github.com/bbangert/velruse/pull/49

**Comment by mmerickel** [comment]
I really appreciate the pull requests. There was a major refactoring of Velruse in the last few months and as a result most of the requests do not apply cleanly. Instead what I have done is opened several issues regarding the features you proposed here and hopefully they can be added back to Velruse in the future in some form or another.

**Comment by kiorky** [comment]
You did not do what you said a while ago.
What was decided on irc was to review/merge/re arrange them quickly (and not blindly, we are maybe agreeing on that point ;))... 

You just let them waiting on github without any remarks and close one year later (this bug was created one month after https://github.com/bbangert/velruse/pull/37).
For the history, i splitted this large request to review chunks more easily. 
At first, i did not think to have to do a so large work on velruse.
So, i spent several hours on making the separate pull requests, and just lose my time.

Well what i will just do in the future is not to use velruse or do my fork without upstreaming with what i'm not easy with.

"""
hopefully they can be added back to Velruse in the future in some form or another.
""" Is just wind.

**Comment by mmerickel** [comment]
I really can appreciate your frustration but understand that velruse did not have a stable api at the time that you submitted the pull requests (it's released as 0.1 alpha). You did not give warning or ask if these features were anything interesting to the project. You submitted the pull requests as very large, barely readable, series of commits which merged many different features in each (even in the resulting requests after the first major one).

It has undergone a refactoring, and the requests do not apply cleanly any longer without major rework of each request. Thus I felt the requests should be closed. I tried to make it clear that while they are closed, the features have merit and they would make good additions to the project.

This is a project that I contribute to in my very limited free time and I apologize that it is not as active as you would like, but please understand that until the project has a stable base it is very difficult to accept lots of contribution. I apologize for that but hopefully it is getting to a place where this won't be a problem in the future.

**Comment by kiorky** [comment]
That's why i ll now try to avoid velruse.

If you did have merged this work when you said, at the time we met and you wanted to, you never would have any merge conflict as it was based on HEAD.

Throwing this (big) work to the trash 5 months saying that you didn't have time for inclusion but in the mean time, you just have also worked on a major velruse rewrite is just self-contradictory.
Most of my bad feelings with velruse remains in the fact that you have done the contrary that you said.

For the record, I have done this stuff for a client, with the client needs & timeline as my primary goal.
If the pullrequests have been discussed / rewritten (even at 100%) / reviewed in a decent timedelta, that's not big of a problem, i would have done it with pleasure.
Now that i know that contributions greater than a css fix have no chance to be reviewed/included, i ll stop my contributions there.

That's hard to predict where this project wants to go, and that's a stopper for me.

We as open source developers are all mainly contributing on our free time, you had activity in the 5 months time, that doesn't explain why you let the pullrequest without a pong which would not have added you extra work as it would have been to me to review my stuff for you just to accept merge, or at most ask for tests and run them to help review.

**Comment by mmerickel** [comment]
I began work on the rewrite 2 months before you submitted your pull request, and no, I didn't have the energy to port all of your changes between the fork that I had created and largely completed before you submitted your pull requests. At any rate, I'm sorry you won't be using velruse any longer.
