### ISSUE TITLE
Normalize 'userid' and 'username'

### ISSUE THREAD

**Issue by Grant1219** [bbangert/velruse#54]
I noticed in some providers like Facebook and QQ the unique ID is stored in 'userid' while providers that use OpenID (Google, Yahoo, etc) store the unique ID in 'username'.

Shouldn't those all be changed to use one common key?

**Comment by mmerickel** [comment]
The portable contacts spec differentiates the `userid` from the `username`, defining the `userid` as a alphanumeric unique identifier from the provider and the `username` would be selected by the user.
