### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by danjac** [bbangert/velruse#7]
The following dependencies are missing from setup:
- routes
- python-memcached

python-memcached should be an optional dependency depending on whether memcached is required or not (same should apply to redis etc)

**Comment by danjac** [comment]
Another broken dependency in the YAML example:

```
File "/home/..../velruse/velruse/utils.py", line 40, in load_package_obj
    __import__(package_name)
ImportError: No module named openidredis
```

Not sure what this refers to, as there is no openredis package in PyPi.

**Comment by bbangert** [comment]
I've fixed this so they're no longer required for other backends. And routes added for core.
