### ISSUE TITLE
AttributeError: add_github_login_from_settings

### ISSUE THREAD

**Issue by JasperVanDenBosch** [bbangert/velruse#71]
I installed the current state of velruse, including https://github.com/bbangert/velruse/pull/70, wanted to try the example pyramid app (i.e. pserve example.ini, with a gtihub provider setup in example.ini) and got the following error below, it seems the config.include behavior doesn't work for me, but I cannot figure out why. Can someone help?

  File "/home/jasper/Projects/velruse-tut/env/local/lib/python2.7/site-packages/paste/deploy/util.py", line 56, in fix_call
    val = callable(_args, *_kw)
  File "/home/jasper/Projects/velruse-tut/env/local/lib/python2.7/site-packages/myapp/**init**.py", line 72, in main
    config.add_github_login_from_settings(prefix='github.')
  File "/home/jasper/Projects/velruse-tut/env/local/lib/python2.7/site-packages/pyramid/config/**init**.py", line 775, in **getattr**
    raise AttributeError(name)
AttributeError: add_github_login_from_settings

pip freeze:

Beaker==1.6.3
Chameleon==2.9.0
Mako==0.7.0
MarkupSafe==0.15
PasteDeploy==1.5.0
PyYAML==3.10
Routes==1.13
WebOb==1.2
anykeystore==0.2
certifi==0.0.8
chardet==1.0.1
distribute==0.6.19
httplib2==0.7.4
nose==1.1.2
oauth2==1.5.211
oauthlib==0.1.3
pyasn1==0.1.3
pyramid==1.3.2
python-openid==2.2.5
repoze.lru==0.5
requests==0.13.0
rsa==3.0.1
translationstring==1.1
venusian==1.0a6
wsgiref==0.1.2
zope.deprecation==4.0.0
zope.interface==4.0.1

**Comment by mmerickel** [comment]
I don't see velruse installed in your environment. You'll need to clone the master branch and install it via `path/to/my/virtualenv/bin/python setup.py develop`.

**Comment by JasperVanDenBosch** [comment]
Sorry I pasted the wrong requirements file, here is the correct one:

Beaker==1.6.3
Chameleon==2.9.1
Mako==0.7.0
MarkupSafe==0.15
PasteDeploy==1.5.0
PyYAML==3.10
Pygments==1.5
Routes==1.13
WebOb==1.2
anykeystore==0.2
argparse==1.2.1
certifi==0.0.8
chardet==1.0.1
distribute==0.6.27
httplib2==0.7.4
myapp==0.0
nose==1.1.2
oauth2==1.5.211
oauthlib==0.1.3
pyasn1==0.1.3
pyramid==1.3.2
pyramid-debugtoolbar==1.0.2
python-openid==2.2.5
repoze.lru==0.5
requests==0.13.0
rsa==3.0.1
translationstring==1.1
velruse==0.3dev
venusian==1.0a6
waitress==0.8.1
wsgiref==0.1.2
zope.deprecation==4.0.0
zope.interface==4.0.1

**Comment by mmerickel** [comment]
I guess you probably didn't include velruse before using it.

```
config.include('velruse.providers.github')

config.add_github_login_from_settings()
```

**Comment by JasperVanDenBosch** [comment]
I am using the exact example pyramid app

**Comment by mmerickel** [comment]
Sorry this is difficult because it's unreleased, I have to make sure I know what version you're using. In development I've simply used `env/bin/python setup.py develop` and `env/bin/pip install -e .`, which have both worked fine because I wasn't installing the app. Patch 70 apparently fixes that issue.

If you are doing the `config.include`, then the `add_github_login_from_settings` should exist on the latest master branch.

**Comment by mmerickel** [comment]
Ah crap, it's called `setup_github_login_from_settings`. I'm going to change that to `add` right now.

**Comment by mmerickel** [comment]
I just pushed this fix, closing the issue. Sorry about that!

**Comment by JasperVanDenBosch** [comment]
Yes, that solves it! Thanks for the effort Michael! I will play around some more with the example and report / contribute if there is anything else useful I can add.
