### ISSUE TITLE
ThirdPartyFailure: Status 401 when trying to use the pyramid_plugin + Twitter

### ISSUE THREAD

**Issue by lmacken** [bbangert/velruse#74]
Hi,
When trying to use the pyramid_plugin demo & Twitter, I'm getting the following traceback:

```
velruse.exceptions.ThirdPartyFailure

ThirdPartyFailure: Status 401: <?xml version="1.0" encoding="UTF-8"?>
<hash>
  <error>Desktop applications only support the oauth_callback value 'oob'</error>
  <request>/oauth/request_token</request>
</hash>
```

**Comment by jayd3e** [comment]
Just went through the process of installing the pyramid_plugin app, and used the twitter provider, in a brand new virtualenv.  I didn't seem to get this error, everything worked fine.  That error message looks incredibly familiar though, and I know for a fact I have gotten it at some point.  Could you give any more details, to try to find the source of the problem?

**Comment by psmit** [comment]
This happens when no callback url is filled in the Twitter settings. Even a fake callback url will solve this problem.

**Comment by mmerickel** [comment]
@lmacken does this solve your issue?

**Comment by mmerickel** [comment]
Closing this until further notice.
